@echo off

set PROJECT_NAME=%1
set PROJECT_VERSION=%2
set REGISTRY_HOST=ARTIFACT_REPOSITORY_URL
set REGISTRY_PATH=ARTIFACT_REPOSITORY_ARTIFACT_PATH
set IMAGE_LATEST_VERSION_TAG=latest

echo Tagging project image
docker tag %PROJECT_NAME%:%PROJECT_VERSION% %PROJECT_NAME%:%IMAGE_LATEST_VERSION_TAG%
docker tag %PROJECT_NAME%:%PROJECT_VERSION% %REGISTRY_HOST%%REGISTRY_PATH%/%PROJECT_NAME%:%PROJECT_VERSION%
docker tag %PROJECT_NAME%:%PROJECT_VERSION% %REGISTRY_HOST%%REGISTRY_PATH%/%PROJECT_NAME%:%IMAGE_LATEST_VERSION_TAG%

echo Pushing project image do registry
docker push %REGISTRY_HOST%%REGISTRY_PATH%/%PROJECT_NAME%:%PROJECT_VERSION% -q
docker push %REGISTRY_HOST%%REGISTRY_PATH%/%PROJECT_NAME%:%IMAGE_LATEST_VERSION_TAG% -q

echo Done.